Readme for operators and running the program
felixrindt/truthtable pull request #10
Opened 2018-11-06 18:56 UTC by BenBals

2018-11-06 20:20 UTC, felixrindt requested changes

2018-11-06 20:20 UTC, felixrindt commented on README.md
> +Please note, that the representation you input will be used in the output.
Please change to `Please note that the output will use the same token representation as your input.`

2018-11-06 20:20 UTC, felixrindt commented on README.md
> +1. the standard input
Should be `The first line of standard input`.

2018-11-06 20:20 UTC, felixrindt commented on README.md
There's a third way: command line argument `python3 truthtable.py "a or b"`

2018-11-06 20:21 UTC, felixrindt commented
Thanks for all your PRs :)

2018-11-07 08:18 UTC, BenBals commented
No problem, thanks for the nice program!

I included your requested changes.

2018-11-07 22:53 UTC, felixrindt requested changes

2018-11-07 22:53 UTC, felixrindt commented on README.md
> +The expression for which the truthtable is to be build is input via one of two ways:
one of three ways then ;-)

2018-11-08 11:24 UTC, BenBals commented on README.md
> +The expression for which the truthtable is to be build is input via one of two ways:
This should be fixed in my latest commit.

2018-11-08 13:04 UTC, felixrindt approved these changes

2018-11-08 13:04 UTC, merged