Use Argparse and add options to not include hlines
felixrindt/truthtable pull request #7
Opened 2018-11-06 18:34 UTC by BenBals

2018-11-06 20:10 UTC, felixrindt requested changes

2018-11-06 20:10 UTC, felixrindt commented on truthtable.py
> +if args.inputFile:
could you keep the condition intact and also check for file name not being `-`?

2018-11-07 08:25 UTC, BenBals commented on truthtable.py
> +if args.inputFile:
I have changed it to include the check for "-" but I am not sure what you mean by keeping the condition intact. (I have never done python before.)

2018-11-07 22:54 UTC, felixrindt commented on truthtable.py
> +if args.inputFile:
I just meant that we shouldn't change the condition. LGTM now

2018-11-07 22:55 UTC, felixrindt commented
Thanks :)

2018-11-07 22:55 UTC, merged